#!/bin/bash

# get tar file from website
# Note : you can check for latest version and put it after /dl/go<latest version number>

wget https://golang.org/dl/go1.21.4.linux-amd64.tar.gz

# Basic extraction process
rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.4.linux-amd64.tar.gz

# Make some zsh configuration
echo $'GOPATH=/root/go-workspace\nexport GOROOT=/usr/local/go\nPATH=$PATH:$GOROOT/bin/:$GOPATH/bin\n'

# Refresh the terminal
source ~/.zshrc

# Show go version installed 
go version
